version: 2.1
orbs:
  node: circleci/node@5.0.3

executors:
  macos-executor:
    macos:
      xcode: 13.4.1

commands:
  build-command:
    steps:
      - run:
          name: Build
          command: yarn build
          no_output_timeout: 30m

  test-command:
    steps:
      - run:
          name: Test
          command: yarn test:web
          no_output_timeout: 30m

  store-results-command:
    steps:
      - store_artifacts:
          path: /Users/distiller/project/apps/web/tests/e2e/screenshots/
      - store_artifacts:
          path: /Users/distiller/project/apps/web/tests/e2e/videos/

jobs:
  synpress-e2e-job:
    executor: macos-executor
    steps:
      - checkout

      - restore_cache:
          name: Restore Chrome install from cache
          key: brew-v1

      - run:
          name: Install Chrome
          command: brew install google-chrome
          no_output_timeout: 30m

      - save_cache:
          name: Save Chrome install to cache
          key: brew-v1
          paths:
            - /Users/distiller/Library/Caches/Homebrew
            - /usr/local/Homebrew

      - restore_cache:
          name: Restore yarn deps from cache
          key: deps-{{ checksum "yarn.lock" }}

      - node/install:
          install-yarn: true
          node-version: "18.12"
      - run:
          name: Install deps
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn
          no_output_timeout: 30m

      - save_cache:
          name: Save yarn deps cache
          key: deps-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - build-command
      - test-command
      - store-results-command

workflows:
  synpress-e2e:
    jobs:
      - synpress-e2e-job
