#![allow(clippy::all)]
//! This module contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod aaveexecutor;
pub mod aavegov;
pub mod aavestrategy;
pub mod arbitrumcore;
pub mod arbitrumtreasury;
pub mod compoundgov;
pub mod dydxexecutor;
pub mod dydxgov;
pub mod dydxstrategy;
pub mod ensgov;
pub mod gitcoingov;
pub mod hopgov;
pub mod interestprotocolgov;
pub mod makerexecutive;
pub mod makerpollcreate;
pub mod makerpollvote;
pub mod makerpollvotearbitrum;
pub mod optimismgov;
pub mod optimismvotemodule_5_4a_8f;
pub mod shared_types;
pub mod uniswapgov;
pub mod zeroxtreasury;
